#ifndef _SYNC_TEMP_H_
#define _SYNC_TEMP_H_

#ifndef SDS_BUF_SIZE_ACCELEROMETER
#define SDS_BUF_SIZE_ACCELEROMETER          8192U
#endif
#ifndef SDS_BUF_SIZE_ACCELEROMETER_TIMESTAMPS
#define SDS_BUF_SIZE_ACCELEROMETER_TIMESTAMPS          8192U
#endif
#ifndef SDS_BUF_SIZE_GYROSCOPE
#define SDS_BUF_SIZE_GYROSCOPE              8192U
#endif
#ifndef SDS_BUF_SIZE_TEMPERATURE_SENSOR
#define SDS_BUF_SIZE_TEMPERATURE_SENSOR     128U
#endif
#ifndef SDS_THRESHOLD_ACCELEROMETER
#define SDS_THRESHOLD_ACCELEROMETER         600U
#endif
#ifndef SDS_THRESHOLD_GYROSCOPE
#define SDS_THRESHOLD_GYROSCOPE             600U
#endif
#ifndef SDS_THRESHOLD_TEMPERATURE_SENSOR
#define SDS_THRESHOLD_TEMPERATURE_SENSOR    4U
#endif

#ifndef REC_BUF_SIZE_ACCELEROMETER
#define REC_BUF_SIZE_ACCELEROMETER          8192U
#endif
#ifndef REC_BUF_SIZE_GYROSCOPE
#define REC_BUF_SIZE_GYROSCOPE              8192U
#endif
#ifndef REC_BUF_SIZE_TEMPERATURE_SENSOR
#define REC_BUF_SIZE_TEMPERATURE_SENSOR     256U
#endif
#ifndef REC_IO_THRESHOLD_ACCELEROMETER
#define REC_IO_THRESHOLD_ACCELEROMETER      0
#endif
#ifndef REC_IO_THRESHOLD_GYROSCOPE
#define REC_IO_THRESHOLD_GYROSCOPE          0
#endif
#ifndef REC_IO_THRESHOLD_TEMPERATURE_SENSOR
#define REC_IO_THRESHOLD_TEMPERATURE_SENSOR 0
#endif

#endif